app/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from sqlalchemy.orm import relationship
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()


class Employee(db.Model, UserMixin):
    __tablename__ = 'employees'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    employee_number = db.Column(db.Integer, unique=True, nullable=False)
    hashed_password = db.Column(db.String(255), nullable=False)

    order = db.relationship('Order', back_populates='employee')

    @property
    def password(self):
        return self.hashed_password

    @password.setter
    def password(self, password):
        self.hashed_password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)


class Menu(db.Model):
    __tablename__ = 'menus'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False)

    items = db.relationship('MenuItem', back_populates='menu')


class MenuItem(db.Model):
    __tablename__ = 'menu_items'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    price = db.Column(db.Float, nullable=False)
    menu_id = db.Column(
        db.Integer,
        db.ForeignKey('menus.id'),
        nullable=False
    )
    menu_type_id = db.Column(
        db.Integer,
        db.ForeignKey('menu_item_types.id'),
        nullable=False
    )

    type = db.relationship('MenuItemType')
    menu = db.relationship('Menu', back_populates='items')


class MenuItemType(db.Model):
    __tablename__ = 'menu_item_types'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)


class Table(db.Model):
    __tablename__ = 'tables'

    id = db.Column(db.Integer, primary_key=True)
    number = db.Column(db.Integer, nullable=False, unique=True)
    capacity = db.Column(db.Integer, nullable=False)

    order = db.relationship('Order', back_populates='table')


class Order(db.Model):
    __tablename__ = 'orders'

    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(
        db.Integer,
        db.ForeignKey('employees.id'),
        nullable=False
    )
    table_id = db.Column(
        db.Integer,
        db.ForeignKey('tables.id'),
        nullable=False
    )
    closed = db.Column(db.Boolean, nullable=False)

    employee = db.relationship('Employee', back_populates='order')
    table = db.relationship('Table', back_populates='order')
    detail = db.relationship(
        'OrderDetail',
        back_populates='order'
    )

    @property
    def total(self):
        return sum([this.item.price for this in self.detail])


class OrderDetail(db.Model):
    __tablename__ = 'order_details'

    id = db.Column(db.Integer, primary_key=True)
    order_id = db.Column(
        db.Integer,
        db.ForeignKey('orders.id'),
        nullable=False
    )
    menu_item_id = db.Column(
        db.Integer,
        db.ForeignKey('menu_items.id'),
        nullable=False
    )

    order = db.relationship('Order', back_populates='detail')
    item = db.relationship('MenuItem')

app/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField, SelectField, SelectMultipleField  # noqa
from wtforms.validators import DataRequired, ValidationError
from app import db


class LoginForm(FlaskForm):
    employee_number = StringField('Employee Number', validators=[DataRequired()])  # noqa
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')


class HostForm(FlaskForm):
    tables = SelectField("Tables", coerce=int)
    servers = SelectField("Servers", coerce=int)
    assign = SubmitField("Assign")


class AddToOrder(FlaskForm):
    menu_item_ids = SelectMultipleField("Menu items", coerce=int)

app/__init__.py
from flask import Flask
from flask_wtf.csrf import CSRFProtect
from .config import Config
from .models import db, Employee
from .routes import orders, session
from flask_login import LoginManager


app = Flask(__name__)
csrf = CSRFProtect(app)
app.config.from_object(Config)
app.register_blueprint(orders.bp)
app.register_blueprint(session.bp)

db.init_app(app)  # Configure the application with SQLAlchemy

login = LoginManager(app)
login.login_view = 'session.login'


@login.user_loader
def load_user(id):
    return Employee.query.get(int(id))

app/routes/orders.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user
from app import db
from app.models import (
      Table,
      Order,
      OrderDetail,
      Employee,
      Menu,
      MenuItem,
      MenuItemType
)
from app.forms import HostForm, AddToOrder
bp = Blueprint('orders', __name__, url_prefix="")


@bp.route("/")
@login_required
def main():
    # Query and filter for open tables
    table_list = Table.query.order_by(Table.number).all()
    open_tables = [(table.id, f"Table {table.number}")
                   for table in table_list
                   if table.id not in [order.id for order in
                   Order.query.filter(Order.closed != False)]]  # noqa
    # Query all employees to assign tables
    employees = Employee.query.order_by(Employee.name).all()
    servers = [(employee.id, f"{employee.name}") for employee in employees]
    form = HostForm(tables=0)
    form.tables.choices = open_tables
    form.tables.choices.insert(0, (0, "Select a Table"))
    form.servers.choices = servers
    form.servers.choices.insert(0, (0, 'Select a Server'))

    orders = Order.query \
        .filter(Order.employee_id == current_user.id) \
        .filter(Order.closed == False)  # noqa

    menu_items = MenuItem.query \
        .join(MenuItemType) \
        .order_by(MenuItemType.name, MenuItem.name) \
        .options(db.joinedload(MenuItem.type))

    menu = {}
    for i in menu_items:
        menu[i.type.name] = []
        menu[i.type.name].append(i)

    return render_template('orders.html',
                           form=form,
                           orders=orders,
                           menu=menu)


@bp.route('/orders/<int:id>/add', methods=['POST'])
@login_required
def add_to_order(id):
    form = AddToOrder()
    # Get the selected items from the food-list form
    form.menu_item_ids.choices = [(item.id, '')
                                  for item in MenuItem.query.all()]
    if form.validate_on_submit():
        order = Order.query.get(id)
        for menu_item_id in form.menu_item_ids.data:
            db.session.add(OrderDetail(order=order, menu_item_id=menu_item_id))
        db.session.commit()
    return redirect(url_for('.main'))


@bp.route('/orders/<int:id>')
@login_required
def show_details(id):
    pass


@bp.route('tables/assign', methods=['POST'])
@login_required
def assign_table():
    


@bp.route('/orders/<int:id>/close', methods=['POST'])
@login_required
def close_order(id):
    order = Order.query.get(id)
    order.closed = True
    db.session.commit()
    return redirect(url_for('.main'))

app/routes/session.py
from flask import Blueprint, redirect, url_for, render_template
from flask_login import current_user, login_user, logout_user
from app.forms import LoginForm
from app.models import Employee

bp = Blueprint('session', __name__, url_prefix="/session")


@bp.route('/', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('orders.main'))
    form = LoginForm()
    if form.validate_on_submit():
        empl_number = form.employee_number.data
        employee = Employee.query \
                           .filter(Employee.employee_number == empl_number) \
                           .first()
        if not employee or not employee.check_password(form.password.data):
            return redirect(url_for('.login'))
        login_user(employee)
        return redirect(url_for('orders.main'))
    return render_template('login.html', form=form)


@bp.route('/logout', methods=['POST'])
def logout():
    logout_user()
    return redirect(url_for('.login'))

app/routes/tableorders.py
from flask import Blueprint

app/templates/base.html
<!DOCTYPE html>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<html>

  <head>
    {% if title %}
    <title>{{ title }} - Order Up!</title>
    {% else %}
    <title>Welcome to Order Up!</title>
    {% endif %}
  </head>

  <body>
    {% if not current_user.is_anonymous %}
    <form method="post" action="{{ url_for('session.logout')  }}">
      {{ form.csrf_token }}
      <button>Logout</button>
    </form>
    {% endif %}
    {% block content %}{% endblock %}
  </body>

</html>

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<form method="post" action="{{ url_for('.login') }}">
  {{ form.csrf_token }}
  <div>
    {{form.employee_number.label }} {{ form.employee_number }}

    {% if form.employee_number.errors %}
    <ul>
      {% for error in form.employee_number.errors %}
      <li>{{ error }}</li>
      {% endfor %}
    </ul>
    {% endif %}
  </div>
  <div>
    {{ form.password.label }} {{ form.password }}

    {% if form.employee_number.errors %}
    <ul>
      {% for error in form.employee_number.errors %}
      <li>{{ error }}</li>
      {% endfor %}
    </ul>
    {% endif %}
  </div>
  <div>{{ form.submit }}</div>
</form>
{% endblock %}

app/templates/orders.html
{% extends "base.html" %}

{% block content %}
<form method="POST">
  {{ form.csrf_token() }}
  <div>
    ASSIGN TABLE
    {{ form.tables }}
    {{ form.servers }}
    {{ form.assign }}
  </div>
</form>
<table>
  YOUR OPEN ORDERS:
  {% for order in orders %}
  <tr>
    <th>Table {{ order.table.number }}</th>
    <td> Current Tab: ${{ order.total }} </td>
    <td>
      <button formaction="{{ url_for('.show_details', id=order.id) }}">ORDER DETAILS</button>
    </td>
    <td>
      <form method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <button formaction="{{ url_for('.close_order', id=order.id) }}">CLOSE ORDER</button>
      </form>
    </td>
    <td>
      <button form="food-list" formaction="{{ url_for('.add_to_order', id = order.id) }}">
        ADD TO ORDER
      </button>
    </td>
  </tr>
  {% endfor %}
</table>
<form id='food-list' method="POST">
  {{ form.csrf_token }}
  {% for food_type in menu %}
  <p>{{ food_type }}</p>
  {% for food_item in menu[food_type] %}
  <input type="checkbox" name="menu_item_ids" id="item_{{ food_item.id }}" value="{{ food_item.id }}">
  <label for="item_{{ food_item.id }}">{{ food_item.name }}</label>
  {% endfor %}
  {% endfor %}
</form>

{% endblock %}

app/templates/tables.html
{% extends "base.html" %}

{% block content %}

{% endblock %}